[package]
name = "anothertls"
version = "0.1.0"
edition = "2021"

[dependencies]
ibig = { version = "0.3.6", default-features = false }

# log = {version = "0.4.17", optional = true }
# [features]
# debug = ["dep:log"]
